# RelativeURLs=true
# CanonifyURLs=true
# languageCode = "en-US"
# defaultContentLanguage = "en"
languageCode = "ja"
defaultContentLanguage = "ja"

# title = "AWS Cloud Security Virtual Event"
title = "AWS Security Roadshow Japan 2021"

theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true



# uglyurls = true
# sectionPagesMenu = "main"
# pygmentsCodeFences = true
# pygmentsStyle = "monokai"

[params]
  ordersectionsby = "weight"
  editURL = ""
  description = "AWS Cloud Security Virtual Event"
  author = "Sumit Patel"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "workshops"
  disableSearch = true
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true
  showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[Languages]
[Languages.en]
title = "AWS Cloud Security Virtual Event"
weight = 2
languageName = "English"
[Languages.ja]
title = "AWS Security Roadshow Japan 2021"
weight = 1
languageName = "日本語"
languageCode = "ja"

